### PR TITLE
DEV: check if eth callback contract exists

### PR DESCRIPTION
**Pull request by apalepu23**
- A "feature" of the EVM is that any nonexistant contracts will always succeed the `call` function. We now properly handle scenarios where an invalid contract address is passed as a failed ETH callback scenario

### CODE REVIEW

**Comment by lenak25** [comment]
@apalepu23 , does this PR still need to be addressed in `P2P` or does #174 include it?
If it is still required, please merge #174 into it, thanks.

**Comment by apalepu23** [comment]
> @apalepu23 , does this PR still need to be addressed in `P2P` or does #174 include it?
> If it is still required, please merge #174 into it, thanks.

Merged #174 into this branch. It introduced some stack limitation errors which got me thinking about necessary fields. I don't believe the `sig` field is required in the task commit receipt (and failure) scenarios, as is already the case in the deployment scenario. So I adjusted the compute events to resemble that of the deployment events to NOT include this sig field. 

Because of this, the following event definitions have changed (https://github.com/enigmampc/enigma-contract/blob/e18cce9f6f469734f445ea29da41e05c224acca4/contracts/impl/EnigmaEvents.sol#L17-L21):
- `ReceiptVerified`
- `ReceiptFailed`
- `ReceiptFailedETH`

**Comment by lenak25** [comment]
Thanks @apalepu23 

> Merged #174 into this branch. It introduced some stack limitation errors which got me thinking about necessary fields.

What about in addition addressing [this](https://github.com/enigmampc/enigma-contract/pull/174/#pullrequestreview-335786635) for meeting the requirement?

**Comment by apalepu23** [comment]
> Thanks @apalepu23
> 
> > Merged #174 into this branch. It introduced some stack limitation errors which got me thinking about necessary fields.
> 
> What about in addition addressing [this](https://github.com/enigmampc/enigma-contract/pull/174/#pullrequestreview-335786635) for meeting the requirement?

This is something I would normally like to fix, but given the limitations of the stack, it actually won't really be possible to remove the redundancy here. `commitReceipt` is a very heavy function that takes many arguments, stores many variables, and emits events that pull variables from deep in the stack (no clear way around this really). One of the workarounds for this that helps is to use arrays instead of the individual items. In order to use a `bytes32[3]` instead of `bytes32[4]`, that would require either a) passing the `taskId` as a separate parameter to the method and using a `bytes32[3]` for the remaining variables, or b) keep the `bytes32[4]` as is and at the time of emitting the event, recreate a `bytes32[3]` array by deconstructing/reconstructing the array accordingly. Unfortunately, both solutions will cause stack problems later on. So while the redundancy exists, it pretty much is the only apparent way to have the function work given its complexity. Hope this helps and is ok with your workstream!

**Comment by lenak25** [comment]
Thanks @apalepu23 for the thorough explanation, I personally inclined to option (b) but I agree with your assessment that if it will cause stack problems we can live with this redundancy.
Will work on the corresponding P2P PR

**Review by lacabra — APPROVED** [review]

**Pull request merged**
